[package]
name = "search-server"
version = "0.1.0"
edition = "2018"

[dependencies]
deunicode = "1.3.1"
libc = "0.2.117"
mupdf = "0.3.0"
search-index = { path = "../search-index" }
serde_json = "1.0"
urlencoding = "2.1.0"

[dependencies.serde]
version = "1.0"
features = ["derive"]
